### PR TITLE
Update firebase data

### LINKED ISSUE #4: update firebase project
update realtime database files and firebase rules to meeet our current needs.

### PR DESCRIPTION
**Pull request by thatfiredev**
This PR should:

- [x] Update Organizing Team and Volunteers
- [x] Update Ticket Information
- [x] Add Previous Speakers
- [x] Update this year's Schedule and Sessions
- [x] Add this year's speakers
- [x] Update all the images

@osvaldoM  I'll be sending a commit for each item on the checklist above to make it easier to review.

Closes #4

### CODE REVIEW

**Review by osvaldoM — APPROVED** [review]
looks good to me.. I suggest we don't wait for the sessions and speakers list before merging this one

**Comment by thatfiredev** [comment]
I understand time is an issue. Let's not merge this PR till it's done, but instead, I'll deploy to firestore every time changes are approved.

**Comment by osvaldoM** [comment]
I understand. thanks. In that case, please proceed with the first deployment after you are done so we can make the announcement.

**Comment by thatfiredev** [comment]
@osvaldoM I've made the firestore deploy. Try running it locally to see the changes. We also need to deploy it to Firebase Hosting. Will you do it or should I?

**Pull request merged**
